modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="Creative Commons Zero 1.0 Universal"
[[mods]] #mandatory
modId="simplesabers" #mandatory
version="1.16.4-1.1.0" #mandatory
displayName="Simple Sabers Mod" #mandatory
authors="Ronnoc" #optional
description='''
This is just a very simple Lightsaber mod developed by TYB-Ronnoc!
'''
